name: Sync Fork

on:
  schedule:
    - cron: '0 7 */3 * *' # at 7:00 every 3 days
  workflow_dispatch: # on button click

jobs:
  sync:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Update forked repository
        uses: tgymnich/fork-sync@v2.0
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: PioMal
          base: main
          head: main
          auto_approve: true

      - name: Notify discord
        uses: th0th/notify-discord@v0.4.1
        if: ${{ always() }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_JOB_NAME: "Tryed to synchronize fork ZMK"
          GITHUB_JOB_STATUS: ${{ job.status }}

            
