name: Sync Fork

on:
  schedule:
    - cron: '0 7 * * 1' # every monday at 7:00
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - name: Update forked repository
        uses: tgymnich/fork-sync@v2.0
        with:
          owner: PioMal
          base: main
          head: main

      - name: discord-notify
        uses: fateyan/action-discord-notifier@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message-title: 'Updated forked ZMK repository'
            
